png(filename="plot4.png", width=480, height=480, units = "px")
par(mfrow=c(2,2))
plot(dataset_sub$DateTime, dataset_sub$GlobalActivePower, type="l", ylab="Global Active Power", xlab="")
plot(dataset_sub$DateTime, dataset_sub$Voltage, type="l", ylab="Voltage", xlab="datetime")
plot(dataset_sub$DateTime, dataset_sub$SubMetering1, type="l", ylab="Energy sub metering", xlab="", ylim=c(0,theMax))
par(new=T)
plot(dataset_sub$DateTime, dataset_sub$SubMetering2, type="l", ylab="Energy sub metering", xlab="", col="red", ylim=c(0,theMax))
par(new=T)
plot(dataset_sub$DateTime, dataset_sub$SubMetering3, type="l", ylab="Energy sub metering", xlab="", col="blue", ylim=c(0,theMax))
legend("topright", bty="n", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lwd=1)
plot(dataset_sub$DateTime, dataset_sub$GlobalReactivePower, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()
